### PR TITLE
[RFR] Fix refresh on Edit clears data

### LINKED ISSUE #451: Refresh clears edit form
admin-on-rest version 0.9.1

Hitting refresh empties the form when editing a resource:

refresh

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #451 

The problem was that we increment the `<Card>` component `key` to force remounting of all input components, which should trigger fetching of related records for `<ReferenceInput>` fields (see #290).

So far so good, but what's surprising is that React first *mounts* the new Card version, then *unmounts* the old Card version. And this is not good for the enclosed form:

1. A new instance of the `<SimpleForm>` component is mounted
2. Because it shares the same form name (`record-form`), the reduxForm instance is unchanged
3. The old instance of the `<SimpleForm>` component is unmounted 
4. Upon unmount, the reduxForm instance is destroyed. Unfortunately, it's the same as before, because it has the name `record-form`
5. All further updates on the form fail because the form is destroyed.

The solution is to create multiple instances of reduxForm to avoid destroying the new one.

### CODE REVIEW

File: src/mui/detail/Edit.js [hunk 1]
```diff
@@ -20,7 +20,6 @@ export class Edit extends Component {
         super(props);
         this.state = {
             key: 0,
-            record: props.data,
```
Comment (fzaninotto) [inline src/mui/detail/Edit.js]: This was used before we moved the state to `<SimpleForm>`. It is not used anymore.
