### PR TITLE
[RFR] Fix CheckboxGroupInput on IE

### LINKED ISSUE #578: CheckboxGroupInput not respond to mouse clicks in IE
Not working checkboxes IE 11.09600.18617, Win 7 pro SP1

image

When I clicked to the checkbox, I see standard Material UI ripple, but the checkbox was disabled.

Example form:

posts.js
```js
import React from 'react';
import {
  Create,
  SimpleForm,
  CheckboxGroupInput
} from 'admin-on-rest/lib/mui';

export const PostCreate = (props) => (
    <Create title="Create a Post" {...props}>
      <SimpleForm>
        <CheckboxGroupInput
            source='control_points'
            choices={ [{ id: 'one', name: 'First' },
            { id: 'two', name: 'Second' }] }
        />
      </SimpleForm>
    </Create>
);
```

app.js
```js
import React from 'react';
import { render } from 'react-dom';
import { simpleRestClient, Admin, Resource } from 'admin-on-rest';
import { PostCreate } from './posts';

render(
    <Admin restClient={simpleRestClient('http://localhost:3000')}>
      <Resource name="posts" create={PostCreate}/>
    </Admin>,
    document.getElementById('root')
);
```

Console is clean.

### PR DESCRIPTION
**Pull request by djhi**
Fixes #578

### CODE REVIEW

File: src/mui/input/CheckboxGroupInput.js [hunk 1]
```diff
@@ -2,9 +2,41 @@ import React, { Component } from 'react';
 import PropTypes from 'prop-types';
 import Checkbox from 'material-ui/Checkbox';
 
-import Labeled from './Labeled';
+import FieldTitle from '../../util/FieldTitle';
 import translate from '../../i18n/translate';
 
+const getStyles = (props, context) => {
```
Comment (fzaninotto) [inline src/mui/input/CheckboxGroupInput.js]: `props` is unused

File: src/mui/input/CheckboxGroupInput.js [hunk 2]
```diff
@@ -107,16 +139,25 @@ export class CheckboxGroupInput extends Component {
 
     render() {
         const { choices, label, resource, source } = this.props;
+        const styles = getStyles(this.props, this.context, this.state);
```
Comment (fzaninotto) [inline src/mui/input/CheckboxGroupInput.js]: `this.state` is unused

File: src/mui/input/CheckboxGroupInput.js [hunk 3]
```diff
@@ -2,9 +2,41 @@ import React, { Component } from 'react';
...
+        baseTheme,
+        textField: {
+            floatingLabelColor,
+            backgroundColor,
+        },
+    } = context.muiTheme;
+
+    return {
+        labelContainer: {
+            fontSize: 16,
```
Comment (fzaninotto) [inline src/mui/input/CheckboxGroupInput.js]: Can't you use the values from the theme for these properties?

File: src/mui/input/CheckboxGroupInput.js [hunk 4]
```diff
@@ -107,16 +139,25 @@ export class CheckboxGroupInput extends Component {
...
+                    </div>
                 </div>
-            </Labeled>
+                {choices.map(this.renderCheckbox)}
+            </div>
         );
     }
 }
 
+CheckboxGroupInput.contextTypes = {
```
Comment (fzaninotto) [inline src/mui/input/CheckboxGroupInput.js]: I prefer to decorate with the `muiThemeable` HOC to have the theme as prop rather than context. Thiat will simplify your tests, too. See `mui/layout/AppBar.js` for an example.

Comment (djhi) [inline src/mui/input/CheckboxGroupInput.js]: Didn't know about the `muiThemeable`, great :)
