### PR TITLE
[RFR] SingleFieldList now accepts a linkType prop

### LINKED ISSUE #740: Allow linkType on Reference*Field
It would be nice if I can specify a linkType on ReferenceManyField or ReferenceArrayField so that when using a SingleFieldList the containing Field would be wrapped with Link.

I could then do something like:

```
<ReferenceManyField label="Comments by" reference="comments" target="post_id" linkType="show">
  <SingleFieldList>
    <ChipField source="author.name" />
  </SingleFieldList>
</ReferenceManyField>
```

Which would make the Chip link to the respective comment.

### LINKED ISSUE #1291: Support resource names containing a slash
**What you were expecting:**
I have a resource `user/comments` and `posts`. In the comment list I have a ReferenceField with refers to which post a comment belongs. So I have it something like:
```jsx
<ReferenceField
  label="Post"
  source="post_id"
  reference="posts"
>
  <TextField source="name" />
</ReferenceField>
```
So the URL of the link I expect it to be `/posts/:id`.

**What happened instead:**
The actual url generated is: `user/posts/:id` which is not expected.

**Environment**

* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue (if applicable):
* React version: 15.6.2
* Browser: Any
* Stack trace (in case of a JS error):

### PR DESCRIPTION
**Pull request by djhi**
- [x] `SingleFieldList` accepts a `linkType` prop (which defaults to `edit`)
- [x] Ensure we correctly handle resource names with slashes in both `SingleFieldList` and `ReferenceField`
- [x] Documentation

Fixes #740 
Fixes #1291

### CODE REVIEW

File: packages/react-admin/src/mui/field/ReferenceField.js [hunk 1]
```diff
@@ -86,36 +87,23 @@ export class ReferenceField extends Component {
         if (!referenceRecord && !allowEmpty) {
             return <LinearProgress />;
         }
-        const rootPath = basePath
-            .split('/')
-            .slice(0, -1)
-            .join('/');
+        const rootPath = basePath.replace(`/${resource}`, '');
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/field/ReferenceField.js]: Smart! But what if the resource name is `edit` (as in video edit) or `show` (as in trade show)? You should handle this special case

File: packages/react-admin/src/mui/field/ReferenceField.js [hunk 2]
```diff
@@ -86,36 +87,23 @@ export class ReferenceField extends Component {
...
-            );
-        }
-        if (linkType === 'show') {
+
+        let resourceLinkPath =
+            linkType === 'edit' || linkType === true
+                ? href
+                : linkType === 'show' ? `${href}/show` : false;
+
+        if (linkType === 'edit' || linkType === true || linkType === 'show') {
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/field/ReferenceField.js]: simplify with a `if(resourceLinkPath)`?

File: packages/react-admin/src/mui/field/ReferenceField.spec.js [hunk 3]
```diff
@@ -54,6 +54,23 @@ describe('<ReferenceField />', () => {
         const linkElement = wrapper.find('WithStyles(Link)');
         assert.equal(linkElement.prop('to'), '/bar/123');
     });
+    it('should render a link to the Edit page of the related record even if the resouce contains slashes', () => {
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/field/ReferenceField.spec.js]: s/resouce/resource/

File: packages/react-admin/src/mui/list/SingleFieldList.js [hunk 4]
```diff
@@ -16,35 +21,106 @@ const styles = {
...
+            ...rest
+        } = this.props;
+
+        return (
+            <div
+                className={classnames(classes.root, className)}
+                {...sanitizeRestProps(rest)}
+            >
+                {ids.map(id => {
+                    const href = linkToRecord(basePath, id);
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/list/SingleFieldList.js]: As it's repeated twice, couldn't you put the edit/show logic inside this `linkToRecord` helper function?

File: packages/react-admin/src/mui/list/SingleFieldList.js [hunk 5]
```diff
@@ -16,35 +21,106 @@ const styles = {
  *         <ChipField source="title" />
  *     </SingleFieldList>
  * </ReferenceManyField>
+ * 
+ * By default, it includes a link to the <Edit> page of the related record
+ * (`/books/:id` in the previous example).
+ *
+ * Set the linkType prop to "show" to link to the <Show> page instead.
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/list/SingleFieldList.js]: You should add that to the `List.md` doc, too.

File: packages/react-admin/src/mui/field/ReferenceField.js (hunk 1 above)
Comment (djhi) [reply packages/react-admin/src/mui/field/ReferenceField.js]: I checked that and when in an edit view, basepath is `/${resource}`, not `/${resource}/edit`

Comment (djhi) [reply packages/react-admin/src/mui/field/ReferenceField.js]: Added tests for those cases

File: packages/react-admin/src/mui/list/SingleFieldList.js (hunk 5 above)
Comment (djhi) [reply packages/react-admin/src/mui/list/SingleFieldList.js]: Done

File: packages/react-admin/src/mui/field/ReferenceField.spec.js [hunk 6]
```diff
@@ -54,14 +55,65 @@ describe('<ReferenceField />', () => {
...
+    });
+    it('should render a link to the Edit page of the related record when the resource is named edit or show', () => {
+        let wrapper = shallow(
+            <ReferenceField
+                record={{ fooId: 123 }}
+                source="fooId"
+                referenceRecord={{ id: 123, title: 'foo' }}
+                reference="edit"
+                resource="show"
+                basePath="/edit"
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/field/ReferenceField.spec.js]: So we're in a list of `show` resources but the basepath is `/edit`? I'm not sure that makes sense, it should be `/show`

File: packages/react-admin/src/mui/field/ReferenceField.spec.js [hunk 7]
```diff
@@ -71,14 +123,49 @@ describe('<ReferenceField />', () => {
...
     });
+    it('should render a link to the Show page of the related record when the resource is named edit or show and linkType is show', () => {
+        let wrapper = shallow(
+            <ReferenceField
+                record={{ fooId: 123 }}
+                source="fooId"
+                referenceRecord={{ id: 123, title: 'foo' }}
+                reference="edit"
+                resource="show"
+                basePath="/edit"
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/field/ReferenceField.spec.js]: same as above, the basepath should be `/show` if the resource is `show`

File: packages/react-admin/src/mui/list/SingleFieldList.spec.js [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+import ChipField from '../field/ChipField';
+
+describe('<SingleFieldList />', () => {
+    it('should render a link to the Edit page of the related record by default', () => {
+        const wrapper = shallow(
+            <SingleFieldList
+                ids={[1, 2]}
+                data={[{ id: 1, title: 'foo' }, { id: 2, title: 'bar' }]}
+                resource="bar"
+                basePath="/bar"
```
Comment (fzaninotto) [inline packages/react-admin/src/mui/list/SingleFieldList.spec.js]: I don't understand this test case. Is it about a reference many of `bar` to `bar`? I suggest you use `post` and `author` or `comment` to make more sense of it.

Comment (djhi) [reply packages/react-admin/src/mui/list/SingleFieldList.spec.js]: The `SingleFieldList` receive the referenced resource as `resource` and the related `basePath`. It does not have knowledge about the original resource which reference its own resource.
