### PR TITLE
[RFR] Fix <NumberField> and <DateField> when record has no value for the source

### LINKED ISSUE #196: NumberField for null value
Hi,
I have records with number fields which may be null.
NumberField throws exception for null, as of toLocaleString() call for null.

### PR DESCRIPTION
**Pull request by fzaninotto**
- [x] Fix `<NumberField>` when record has no value for the source
- [x] Fix `<DateField>` when record has no value for the source

Closes #196

### CODE REVIEW

File: src/mui/field/DateField.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ import get from 'lodash.get';
 const DateField = ({ source, record, showTime = false, elStyle }) => {
     if (!record) return null;
     const value = get(record, source);
+    if (value == null) return null;
```
Comment (djhi) [inline src/mui/field/DateField.js]: Shouldn't we allow to customize what is displayed when value is null ?

File: src/mui/field/NumberField.js [hunk 2]
```diff
@@ -33,8 +33,10 @@ const hasNumberFormat = !!(typeof Intl === 'object' && Intl && typeof Intl.Numbe
  */
 const NumberField = ({ record, source, locales, options, elStyle }) => {
     if (!record) return null;
-    if (!hasNumberFormat) return <span style={elStyle}>{get(record, source)}</span>
-    return <span style={elStyle}>{get(record, source).toLocaleString(locales, options)}</span>;
+    const value = get(record, source);
+    if (value == null) return null;
```
Comment (djhi) [inline src/mui/field/NumberField.js]: Same question

File: src/mui/field/DateField.js (hunk 1 above)
Comment (fzaninotto) [inline src/mui/field/DateField.js]: We don't do it anywhere else. And I don't see what you'd want to display if there is no value?
