### PR TITLE
[RFR] Fix Edit view shows stale data

### LINKED ISSUE #305: "edit" functionality not using latest state
Hello,

Not sure if this is happening for anyone else, but I have a datagrid that gets displays a list of records.  (/users)

If I then click on a link to go to an individual record, that does a GET request to get /users/<id> - however the data shown at this point is the data retrieved when getting the list of records (i.e. from /users).

If I then click on 'refresh', it updates to show the data from /users/<id>. So it would appeat that currently the request to /users/<id> is used as an existence check, but not to update the data already received. Is this expected behaviour??

### PR DESCRIPTION
**Pull request by fzaninotto**
Our optimistic rendering strategy used to conflict with redux-form. When navigating to an `<Edit>` view, we use the current state (usually filled up by the `<List>` view) to prefill the form via redux-form's `initialValues`. Then we fetch the up-to-date record via a `CRUD_GET_ONE` action. When the REST server arrives, we update the state with the updated record, which updates the (connected) `<Edit>` view. 

But rerendering the `<Edit>` view just updates the ùinitialValues`, and by default redux-form doesn't listen to changes of this attribute (see https://github.com/erikras/redux-form/issues/176 and http://redux-form.com/6.5.0/examples/initializeFromState/). Passing `enableReinitialize: true` solves the problem.

Closes #305

### CODE REVIEW

File: src/reducer/resource/data.js [hunk 1]
```diff
@@ -45,8 +45,10 @@ const addRecords = (newRecords = [], oldRecords) => {
     // remove outdated old records
     const latestValidDate = new Date();
     latestValidDate.setTime(latestValidDate.getTime() - cacheDuration);
-    const oldValidRecordIds = Object.keys(oldRecords.fetchedAt)
-        .filter(id => oldRecords.fetchedAt[id] > latestValidDate);
+    const oldValidRecordIds = oldRecords.fetchedAt
```
Comment (fzaninotto) [inline src/reducer/resource/data.js]: This change allows me to import a serialized state (exported via the redux dev tools). This was required to test the patch.
