### PR TITLE
[RFR] Fix list optimistic rendering

### LINKED ISSUE #493: Optimistic rendering of List may create errors due to outdated data
test usage: 

aor 0.9.2,   latest admin-on-rest-demo

reproduce:

 - change code in data.js:   const cacheDuration = 10 * 60 * 1; // change to very short cache timeout
  - click ui: Customers -> Reviews -> Customers

throw:

>  index.js:44 Uncaught (in promise) TypeError: Cannot read property 'total_spent' of undefined(…)

problem: 
    Reviews call 'GET_MANY_REFERENCE', triger delete outdated records(customers data), but ids of customers resource still exists in redux state. When Customers page load again, it will load ids in redux state to init, but data have been deleted.

fix:
```
    in /mul/list/List.js, 
    componentWillUnmount() {
        ...
        this.props.clearListIDs(this.props.resource);  // delete my ids list in redux state
    } 
```

### PR DESCRIPTION
**Pull request by djhi**
Fixes #493

### CODE REVIEW

File: src/reducer/resource/list/ids.js [hunk 1]
```diff
@@ -1,10 +1,57 @@
...
+    }, []);
+    // remove outdated old records
+    const latestValidDate = new Date();
+    latestValidDate.setTime(latestValidDate.getTime() - cacheDuration);
+    const oldValidRecordIds = oldRecords.fetchedAt
+        ? Object.keys(oldRecords.fetchedAt)
+            .filter(id => oldRecords.fetchedAt[id] > latestValidDate)
+        : [];
+    const oldValidRecords = oldValidRecordIds.reduce((prev, id) => {
+        prev[id] = oldRecords[id]; // eslint-disable-line no-param-reassign
```
Comment (kimkha) [inline src/reducer/resource/list/ids.js]: I think this line is wrong. `oldRecords` is an array of ids, so `oldRecords[id]` will be no meaning.

For example, with `oldRecords = ['e43a...', 'e45a...']`, if we want to get value, we must use `oldRecords[0]` (or `1`), not `oldRecords['e43a...']`. Right?

Comment (fzaninotto) [inline src/reducer/resource/list/ids.js]: probably... I need to look at it more deeply. In the meantime, as I want to release 1.1.0, I must revert the change.

Comment (kimkha) [inline src/reducer/resource/list/ids.js]: I think the correct one is `const oldValidRecords = oldValidRecordIds;`. Don't need to `reduce`...

@djhi What do you think?
