### PR TITLE
[RFR] Fix ReferenceField should not fetch null values

### LINKED ISSUE #617: ReferenceField doesn't allow undefined values
Use case:
I have an optional reference field on my entity whose value is either `undefined` or an id of another entity

Expected: 
admin-on-rest checks the value of the record with the given `source` prop, and if undefined displays nothing, otherwise a request for the referenced entity is sent and the reference child field is displayed

Actual:
admin-on-rest sends a GET_MANY request with parameter `ids` as `["undefined"]`

### PR DESCRIPTION
**Pull request by djhi**
Fixes #617

### CODE REVIEW

File: src/mui/field/ReferenceField.js [hunk 1]
```diff
@@ -38,15 +38,22 @@ import linkToRecord from '../../util/linkToRecord';
...
     componentWillReceiveProps(nextProps) {
         if (this.props.record.id !== nextProps.record.id) {
-            this.props.crudGetOneReference(nextProps.reference, get(nextProps.record, nextProps.source));
+            this.fetchReference(nextProps);
         }
     }
 
+    fetchReference(props) {
+        const source = get(props.record, props.source);
+        console.log({ source });
```
Comment (zyhou) [inline src/mui/field/ReferenceField.js]: Debug console spotted
