### PR TITLE
[RFR] Fix Refresh button doesn't refresh reference fields

### LINKED ISSUE #279: Refresh should refresh all nested reference fields.
If you have a ReferenceManyField in an Edit component and you click refresh.
It will only update the data from the record itself.
It won't fire requests for the ReferenceManyFields.

### PR DESCRIPTION
**Pull request by fzaninotto**
To force fetching again data in inner components (e.g. in `<ReferenceField>`), we change the value of the `key` prop on reload.

(`forceUpdate()` should also work, but a) [it's discouraged](http://stackoverflow.com/a/35004739/1333479), and b) it doesn't work for some reason)

- [x] Proof of concept
- [x] Backport to master
- [x] Test more

Note: This doesn't work on the blog example (i.e. no refreshing of the referenne fields) because `aor-json-rest-client` returns always the same record and therefore passes the strict equality check. I'll fix that in the related repository.

Fixes #279

### CODE REVIEW

**Comment by fzaninotto** [comment]
Now RFR

File: src/mui/detail/Edit.js [hunk 1]
```diff
@@ -64,10 +72,11 @@ export class Edit extends Component {
 
     render() {
         const { actions = <DefaultActions />, children, data, hasDelete, hasShow, id, isLoading, resource, title } = this.props;
+        const { key } = this.state;
         const basePath = this.getBasePath();
 
         return (
-            <Card style={{ margin: '2em', opacity: isLoading ? 0.8 : 1 }}>
+            <Card style={{ margin: '2em', opacity: isLoading ? 0.8 : 1 }} key={key}>
```
Comment (djhi) [inline src/mui/detail/Edit.js]: evil jsx literal !

File: src/mui/list/List.js [hunk 2]
```diff
@@ -153,11 +158,12 @@ export class List extends Component {
 
     render() {
         const { filter, pagination = <DefaultPagination />, actions = <DefaultActions />, resource, hasCreate, title, data, ids, total, children, isLoading } = this.props;
+        const { key } = this.state;
         const query = this.getQuery();
         const filterValues = query.filter;
         const basePath = this.getBasePath();
         return (
-            <Card style={{ margin: '2em', opacity: isLoading ? 0.8 : 1 }}>
+            <Card style={{ margin: '2em', opacity: isLoading ? 0.8 : 1 }} key={key}>
```
Comment (djhi) [inline src/mui/list/List.js]: same

File: src/mui/detail/Edit.js (hunk 1 above)
Comment (fzaninotto) [inline src/mui/detail/Edit.js]: depends on `isLoading`, so it's dynamic. It could be optimized, but that's not the purpose of that PR. Same for your other comment.

Comment (djhi) [inline src/mui/detail/Edit.js]: true, misread...
