### PR TITLE
[RFR] Fix multiple ReferenceFields in a list incorrectly loads data

### LINKED ISSUE #98: Multiple ReferenceFields in a List load data from last 'reference'
When placing multiple reference fields in a List, any API requests for reference data points to the reference that is used last. This causes the earlier reference fields to load forever.

Admin List Display
screen shot 2016-10-17 at 10 34 25 am

List Source, containing one ReferenceField with a reference set to 'restaurants' and one ReferenceField with a reference set to 'regions'
screen shot 2016-10-17 at 10 35 29 am

Network requests... both hitting 'regions'
screen shot 2016-10-17 at 10 34 51 am

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #98

### CODE REVIEW

File: src/sideEffect/saga/referenceFetch.js [hunk 1]
```diff
@@ -11,34 +11,33 @@ import { crudGetMany } from '../../actions/dataActions';
...
-let ids = {};
+const ids = {};
+const tasks = {};
 
 // see http://yelouafi.github.io/redux-saga/docs/recipes/index.html#debouncing
-function *fetchReference(resource) {
+function* fetchReference(resource) {
     // combined with cancel(), this debounces the calls
     yield call(delay, 50);
-    yield Object.keys(ids).map(reference =>
```
Comment (fzaninotto) [inline src/sideEffect/saga/referenceFetch.js]: There was a logic error here: if we decide to fetch one resource, we shouldn't iterate on the keys of `ids`. We know the resource to fetch.

File: src/sideEffect/saga/referenceFetch.js [hunk 2]
```diff
@@ -11,34 +11,33 @@ import { crudGetMany } from '../../actions/dataActions';
...
-    let task;
+function* watchFetchReference() {
     while (true) { // eslint-disable-line no-constant-condition
         const { payload } = yield take(CRUD_GET_ONE_REFERENCE);
         const { id, resource } = payload;
         if (!ids[resource]) {
             ids[resource] = {};
         }
         ids[resource][id] = true; // fast UNIQUE
-        if (task) {
```
Comment (fzaninotto) [inline src/sideEffect/saga/referenceFetch.js]: Doesn't work if there are two distinct `resource`s
